### ISSUE TITLE
Connection failure after successful login

### ISSUE THREAD

**Issue by Dimlitter** [zhangt2333/actions-easyconnect#2]
easyconnect似乎成功的跑起来了，但是ip却没有改变
能否给个更为详细的使用例子呢？谢谢
![image](https://user-images.githubusercontent.com/68945228/166127075-9defda4c-7a49-4a40-b060-2534cc0a722d.png)

**Comment by zhangt2333** [comment]
可能是 easyconnect 重新封装了 source IP 和 dist IP.

实际上这个 actions 是能用的，你可以通过 [Used by](https://github.com/zhangt2333/actions-easyconnect/network/dependents) 看看其他开发者是如何使用的。

虽然我对这个问题很感兴趣，但我此时此刻并不想花时间去折腾。

> 我(们)不太关心发出去的网络包为什么把真实IP透出去了，只要能连通内网就行

如果你对这个问题的原因很感兴趣，可以了解一下 SSL VPN 的原理，考虑用 Wireshark 等软件进行抓包，查看这个包的报文头是否真的被重新包装。期待你成功找到结论并分享给我们。

**Comment by Dimlitter** [comment]
哦不不，我的意思是`没有成功连接上内网`，而不是`未能隐藏真实ip`

![image](https://user-images.githubusercontent.com/68945228/166137914-b8219d8c-5e6e-4e98-93c7-25db7ad03929.png)

> 以及这个easyconnect连接成功的判断似乎不太准确？

**Comment by zhangt2333** [comment]
截止至今 sdu 和 [sysu](https://github.com/gitgiter/jksb_sysu/actions/runs/2251547710) 也是能正常使用的。

如果是已经 `easyconn login success!` 还无法连通内网，那具体原因我也不会排，或和 easyconnect 版本有关，或和证书问题相关。

也可以试试 Docker 封装 easyconn 的[源仓库](https://github.com/Hagb/docker-easyconnect)（本项目是基于此仓库的）

**Comment by Dimlitter** [comment]
嗯，多谢解惑。

现在我转向用`selenium`走`webvpn`了..

不过还是谢谢热心解答！
